# Netlify Build Configuration
# This file provides explicit instructions, overriding Netlify's auto-detection.

[build]

  command = "ng build"

  # 2. The correct publish directory for a standard Angular build.
  #    This is the folder that actually gets created.
  publish = "dist/currency-converter/"

# This tells Netlify to use a standard build image and disables the
# conflicting Angular runtime plugin.
[functions]
  node_bundler = "esbuild"

